### ISSUE TITLE
add question

### ISSUE THREAD

**Issue by icarosun** [icarosun/quizz#1]
Question 3 from SEEG quizz.

Siga as seguintes instruções: 
- [x] Clone o projeto em sua máquina; 
- [x] cd quizz/ 
- [x] Execute o código com o comando `flutter run`;
- [x] Crie uma branch com o nome: **add_question_3**;
- [x] Adicione a nova questão na pasta https://github.com/icarosun/quizz/blob/main/lib/viewmodel/quizz_gamemodel.dart
- [x] Execute o código;
- [x] Verifica se tá funcionando;
- [x] Git add;
- [x] Git commit "add: question 3 seeg";
- [x] git push orgin add_question_3;
- [x] Apertar em finalizar issue;

**Comment by Alexon45** [comment]
concluído
